### ISSUE TITLE
[FEAT] Release Tool Should Cleanup on Error

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1768] opened 2021-08-20 15:15 UTC
# :bulb: Feature request

## Feature Name

Release Tool Should Cleanup on Error

## The Desired Behavior

When the release tool errors, for example during the build, it should still perform cleanup actions.

## Your Use Case

As a maintainer, I don't want to have to manually delete the temporary release branch when the release task fails.

**Comment by damienwebdev** [comment] 2022-01-02 21:04
Duplicate of #1139

**Closed by damienwebdev** 2022-01-02 21:04 UTC
Labels: feat
